### PR TITLE
CLOUDP-205479: Fixed missing changes for the AtlasProject crd

### PR DESCRIPTION
**Pull request by igor-karpukhin**
### All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Review by josvazg — APPROVED** [review]
LGTM

Was this the result of running some tool?

**Review by s-urbaniak — APPROVED** [review]
how come we didn't catch this earlier? @josvazg qq: is this part of your work?

**Comment by helderjs** [comment]
> LGTM
> 
> Was this the result of running some tool?

When you make a change in a CRD type, you should run `make generate manifests` to have the generated deep copies go files, and the changes reflected in the manifests base files

**Comment by helderjs** [comment]
> how come we didn't catch this earlier? @josvazg qq: is this part of your work?

@s-urbaniak I mentioned the same case in my current PR

**Review by helderjs — APPROVED** [review]

**Comment by igor-karpukhin** [comment]
PTAL once again. The local deployment was broken as well

**Review by helderjs — APPROVED** [review]

**Pull request merged**
