### PR TITLE
Integrate Atlas Operator with Red Hat Database-as-a-Service (DBaaS) Operator

### PR DESCRIPTION
**Pull request by jianrongzhang89**
This PR is to enhance the Atlas Operator for integration with the Red Hat DBaaS Operator (https://github.com/RHEcosystemAppEng/dbaas-operator) on OpenShift. It introduces 3 controllers:
1) DBaaS Registration
If the DBaaS Operator has been deployed in the OpenShift Cluster, the Atlas Operator automatically creates a cluster-level DBaaSProvider (https://github.com/RHEcosystemAppEng/dbaas-operator/blob/main/config/crd/bases/dbaas.redhat.com_dbaasproviders.yaml) custom resource (CR) object mongodb-atlas-registration to automatically register itself with the DBaaS Operator. 
2) MongoDBAtlasInventory
For the discovery of Atlas clusters and database instances for applications to connect to.
3) MongoDBAtlasConnection
A MongoDBAtlasConnection CR provides the connection details along with DB credentials. It allows application developers to connect to the databases through the Service Binding Operator (https://github.com/redhat-developer/service-binding-operator). 

Testing with the DBaaS Operator and the Service Binding Operator completed on local OpenShift 4.7 cluster.

### CODE REVIEW

**Comment by jeremyary** [comment]
@jamesbroadhead @gssbzn hey guys, we're not sure who's best be to tag for reviews given that Anton was our previous point of contact. Any guidance there? Thanks!

**Comment by jamesbroadhead** [comment]
@jeremyary & @jianrongzhang89 Hi there - This is a big & interesting change! Probably best to start discussing with @jasonmimick, the Product Manager for the Operator. 
You can contact us in the CoreOS slack, or by email

**Comment by jianrongzhang89** [comment]
> @jeremyary & @jianrongzhang89 Hi there - This is a big & interesting change! Probably best to start discussing with @jasonmimick, the Product Manager for the Operator.
> You can contact us in the CoreOS slack, or by email
Thanks, @jamesbroadhead @jasonmimick.

**Comment by fabritsius** [comment]
This PR seems outdated. Feel free to create a new one if you need.
Thank you 🙏

**Pull request closed without merging**
