### PR TITLE
CLOUDP-211533: Bump Kubernetes Atlas Operator 2.0 go module major version to 2

### PR DESCRIPTION
**Pull request by s-urbaniak**
### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Comment by josvazg** [comment]
What this done using some tooling or script? I would review that instead.

**Comment by s-urbaniak** [comment]
@josvazg to my knowledge automated tooling does not exist for major bumps. I have done this using regex magic.

**Comment by s-urbaniak** [comment]
(and manual changes)

**Comment by josvazg** [comment]
I see, for these kind of mass changes I would prefer to check the script that was used if possible, even and specially if it was ad-hoc for this.

Otherwise I think we can trust the tests will pick up more issues that us trying to skim 208 files in a single review.

**Comment by s-urbaniak** [comment]
Yes I agree, as mentioned, no script was used. It seems the community has not come up with automation here yet.

**Comment by josvazg** [comment]
I believe the current failures might be transient most likely. I have kicked a re-run, and we can check the result.

**Comment by s-urbaniak** [comment]
fwiw confirm that we can import both v1 and v2 from this PR:
```
$ cat go.mod
module example.com/test

go 1.21.3

replace github.com/mongodb/mongodb-atlas-kubernetes/v2 => /Users/s.urbaniak/src/mongodb-atlas-kubernetes

require (
	github.com/mongodb/mongodb-atlas-kubernetes v1.9.1
	github.com/mongodb/mongodb-atlas-kubernetes/v2 v2.0.0
)
```

```
package main

import (
	atlasv1 "github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1"
	atlasv2 "github.com/mongodb/mongodb-atlas-kubernetes/v2/pkg/api/v1"
)

func main() {
	_ = atlasv1.AWSProviderConfig{}
	_ = atlasv2.AWSProviderConfig{}
}
```

**Review by igor-karpukhin — APPROVED** [review]
Good job! 👍

**Review by josvazg — APPROVED** [review]
LGTM

**Pull request merged**
