### PR TITLE
CLOUDP-269877: pkg/controller: remove resource watcher

### PR DESCRIPTION
**Pull request by s-urbaniak**
Physical removal of resource watcher as it is not used any more.

### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes-template.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ah, this indeed must build on top of https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1785. So ignore those commits here.

**Comment by s-urbaniak** [comment]
(the actual commit to review is https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1785/commits/03b2fb6d603d7b1588f02ac65141df27459e007d)

**Review by josvazg — COMMENTED** [review]
LGTM but will wait for rebase after #1784 merges to approve

**Review by josvazg — APPROVED** [review]
LGTM!

**Pull request merged**
