### PR TITLE
CLOUDP-259884: pkg/indexer: add bcp indexer name

### PR DESCRIPTION
**Pull request by s-urbaniak**
### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes-template.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Review by josvazg — APPROVED** [review]

**Review by helderjs — APPROVED** [review]

**Review by igor-karpukhin — APPROVED** [review]

**Comment by igor-karpukhin** [comment]
`make fix-lint`

**Comment by josvazg** [comment]
Fix linter and we should be good to go

**Comment by s-urbaniak** [comment]
yep yep

**Comment by s-urbaniak** [comment]
currently on another branch, will do once ready :)

**Pull request merged**
