### PR TITLE
CLOUDP-167740: Fix connection secrets generation for DBUsers in separated namespaces

### LINKED ISSUE #899: New AtlasDeployment does not generate connection secrets for existing project AtlasDatabaseUser in different namespace
**What did you do to encounter the bug?**

- Create `AtlasProject` (namespace: mongodb-atlas-system)
- Create `AtlasDeployment` "dep1" (namespace: mongodb-atlas-system)
- Create `Secret` password Ref and `AtlasDatabaseUser` user1 (namespace: default)
  - verified `Secret` project-dep1-user1 exists (namespace: default)
- Create `Secret` password Ref and `AtlasDatabaseUser` user2 (namespace: mongodb-atlas-system)
  - verified `Secret` project-dep2-user2 exists (namespace: mongodb-atlas-system)
- Create `AtlasDeployment` "dep2" (namespace: mongodb-atlas-system)
  - verified `Secret` project-dep2-user2 exists (namespace: mongodb-atlas-system)
  - missing `Secret` project-dep2-user1  (namespace: default)

**What did you expect?**

A `Secret` project-dep2-user1 (namespace: default) to be created.

**What happened instead?**

When the new AtlasDeployment was created, the existing AtlasDatabaseUser in the same namespace had a credentials + connection string Secret created, but AtlasDatabaseUser resources in other namespaces did not.

**Operator Information**
 - Operator Version: 1.6.1

**Kubernetes Cluster Information**
 - Distribution: EKS
 - Version: 1.24.10

**Additional context**

Of note, the operator doesn't seem to log any information about the `Secret` reconciliation that occurred for `AtlasDatabaseUser` user2 in the same namespace

### PR DESCRIPTION
**Pull request by helderjs**
### All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

closes #899

### CODE REVIEW

**Review by igor-karpukhin — APPROVED** [review]
Looks good 👍

**Review by fabritsius — APPROVED** [review]
Looks Great 👍

**Review by fabritsius — APPROVED** [review]
Looks Great 👍

**Review by igor-karpukhin — APPROVED** [review]
Looks good 👍

**Review by igor-karpukhin — APPROVED** [review]

**Pull request merged**
