### PR TITLE
Ensure tests checkout PR branch

### PR DESCRIPTION
**Pull request by josvazg**
If not explicit, on some PR or push events it might checkout main instead, which is not what we want on PR tests.

### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

### CODE REVIEW

**Review by roothorp — APPROVED** [review]
Have you got this working on a fork somewhere?

**Comment by josvazg** [comment]
> Have you got this working on a fork somewhere?

I tested here directly. I will run cloud tests so that we can double check it picked up the right PR branch to checkout also there.

**Comment by josvazg** [comment]
> looks like it's still checking out main...

Seems when you re-label it does not work, I guess `${{ github.head_ref || github.ref }}` renders nothing so it goes to defaults.

I am going to add some traces.

**Comment by josvazg** [comment]
Seems `ref: ${{github.event.pull_request.head.sha}}` is the answer everywhere, independent of the trigger event.

**Pull request merged**
