### PR TITLE
CLOUDP-186801: disable depguard linter

### PR DESCRIPTION
**Pull request by josvazg**
### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Comment by helderjs** [comment]
@josvazg We should not disable the depguard linter, but update golangci-lint in the project and adjust its config.

**Comment by josvazg** [comment]
> @josvazg We should not disable the depguard linter, but update golangci-lint in the project and adjust its config.

This change is to make the development environment `make lint` behaviour match the current CI state.

What is the value of having development fail for something the CI is not checking yet?
We can enable it back on the same PR that fixes the config and would make the CI use depguard.

**Comment by helderjs** [comment]
@josvazg Why do you think CI is not checking it?
The latest depguard version has changed its default behavior, requiring to explicitly setting a config for it.
https://github.com/OpenPeeDeeP/depguard/issues/55
https://github.com/OpenPeeDeeP/depguard/issues/49

**Comment by josvazg** [comment]
> 

It seemed so, because `make lint` in development fails with a lot of `depguard` failures. In any case, the point of this PR is to fix the development behavior by default, while the proper fix gets deployed to both dev and the CI.

**Comment by josvazg** [comment]
If I understood correctly, I could alternatively just drop this PR and instead keep on using the same linter version as the CI to have the same results.
I will be closing this then.
Thanks!

**Pull request closed without merging**
