### PR TITLE
CLOUDP-280230: Refactor adds Project Dual Reference

### PR DESCRIPTION
**Pull request by josvazg**
While the refactor change accept many files, there are only a few key places that are key:
- The new **ProjectDualReference** at `pkg/api/v1/projectref.go` encapsulates together the 3 fields that are required for all CRDs that depend on a project and have dual mode of operation with independent IDs and Kubernetes references.
- The credentials types at `pkg/api/credentials.go` are simplifies all types but **CredentialsProvider** interface disappear and a new **ObjectwithCredentials** allows indexers to define kubertenes objects that carry credentials, such is the case of these dual references.
- All CRDs supporting independent usage are changed to use the new **ProjectDualReference**.

All the rest of changes are derived from there:
- Some CRD descriptions are changes to become consistent under `config/crd/bases`. **There are no changes to the YAML**, this is a refactor.
- Some reference namings are corrected to be consistent across all types now.
- All tests need to be fixed with the new type shape, fields are moved around, and sometimes renamed.

### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@josvazg what ticket does this change refer to?

**Comment by josvazg** [comment]
> @josvazg what ticket does this change refer to?

It is part of the network peerings work, let me update.

**Comment by josvazg** [comment]
CLOUDP-280230

**Comment by josvazg** [comment]
wrong branch name

**Comment by josvazg** [comment]
Replaced by #1971

**Pull request closed without merging**
