### PR TITLE
CLOUDP-248533: Fix X509Type as a enum

### PR DESCRIPTION
**Pull request by josvazg**
### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

### CODE REVIEW

**Comment by josvazg** [comment]
Bad news here, I thought this change introduced some errors that I had to find and fix. But it is worse actually, introduces new flakiness. It either creates such flakiness somehow or increases the likelihood of an issue that was already there was did not see so flaky before.

**Comment by josvazg** [comment]
Today flakiness might have gone away locally and in the CI, not sure how to proceed. Will wait for tests to complete.

**Comment by josvazg** [comment]
Only serverless failed, which is a well known flaky from before so, maybe we can merge this already.

**Comment by josvazg** [comment]
related to CLOUDP-248533

**Review by helderjs — APPROVED** [review]

**Pull request merged**
