### PR TITLE
CLOUDP-228583: migrate private endpoints to new Atlas SDK

### PR DESCRIPTION
**Pull request by s-urbaniak**
### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Review by josvazg — COMMENTED** [review]
LGTM, not sure about the the cloud test failures though

**Comment by s-urbaniak** [comment]
The e2e test failurs need investigation, I believe they are legit.

**Comment by s-urbaniak** [comment]
`privatelink` e2e is consistently broken, I bet I have introduced a bug here, investigating.

**Comment by s-urbaniak** [comment]
I have a local reproducer, investigating...

**Comment by s-urbaniak** [comment]
fixed one issue but i am still seeing e2e failures locally.

**Comment by s-urbaniak** [comment]
one more last failure to investigate 😬

**Review by josvazg — APPROVED** [review]

**Review by helderjs — APPROVED** [review]

**Pull request merged**
