### PR TITLE
CLOUDP-130484: Refactor the Advanced Deployment Handler

### LINKED ISSUE #606: Operator fails while reconciling cluster autoscaling events
**What did you do to encounter the bug?**
We had existing atlas clusters created/managed by Atlas operator Alpha version. While upgrading to the operator's GA version, we changed the k8s manifest w.r.t `advancedDeploymentSpec` of the `AtlasDeployment` CR spec. This new spec had instance size changed from M10 to M40 (which was within the autoscaling limits of the existing atlas cluster). 

**Previous Spec:**
```console
    autoScaling:
      compute:
        enabled: true
        scaleDownEnabled: true
      diskGBEnabled: true
    diskSizeGB: 40
    mongoDBMajorVersion: "4.4"
    numShards: 1
    pitEnabled: false
    providerBackupEnabled: true
    providerSettings:
      autoScaling:
        compute:
          maxInstanceSize: M40
          minInstanceSize: M10
      instanceSizeName: M10
      providerName: GCP
      regionName: WESTERN_EUROPE
```

New Spec:
```console
    advancedDeploymentSpec:
      backupEnabled: true
      diskSizeGB: 40
      mongoDBMajorVersion: "4.4"
      pitEnabled: false
      replicationSpecs:
      - numShards: 1
        regionConfigs:
        - electableSpecs:
            instanceSize: M40
          autoScaling:
            compute:
              enabled: true
              maxInstanceSize: M40
              minInstanceSize: M10
              scaleDownEnabled: true
            diskGBEnabled: true
          providerName: GCP
          regionName: WESTERN_EUROPE
```

This resulted in a confusing error:

```error
{"level":"INFO","time":"2022-07-15T10:22:38.851Z","msg":"-> Starting AtlasDeployment reconciliation","atlasdeployment":"platform/singletons-locking","spec":{"projectRef":{"name":"singletons-europe-west1.gcp.escemo.com-1","namespace":""},"advancedDeploymentSpec":{"backupEnabled":true,"diskSizeGB":40,"mongoDBMajorVersion":"4.4","name":"locking","pitEnabled":false,"replicationSpecs":[{"numShards":1,"regionConfigs":[{"electableSpecs":{"instanceSize":"M40"},"autoScaling":{"diskGBEnabled":true,"compute":{"enabled":true,"scaleDownEnabled":true,"minInstanceSize":"M10","maxInstanceSize":"M40"}},"providerName":"GCP","regionName":"WESTERN_EUROPE"}]}]},"backupRef":{"name":"","namespace":""}},"status":{"conditions":[{"type":"Ready","status":"False","lastTransitionTime":"2022-07-14T16:26:30Z"},{"type":"ValidationSucceeded","status":"True","lastTransitionTime":"2022-07-14T16:26:30Z"},{"type":"DeploymentReady","status":"False","lastTransitionTime":"2022-07-14T16:26:30Z","reason":"DeploymentNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/60db89b8c5283149d39324aa/clusters/locking: 400 (request \"ATTRIBUTE_READ_ONLY\") The attribute createDate is read-only and cannot be changed by the user."}],"observedGeneration":1,"stateName":"UPDATING"}}
{"level":"INFO","time":"2022-07-15T10:22:38.851Z","msg":"Reading Atlas API credentials from the AtlasProject Secret platform/singletons-europe-west1.gcp.escemo.com-1-api-key","atlasdeployment":"platform/singletons-locking"}
```
We got to know about this when we ran the operator in debug mode and saw this in the logs:

```debug
{"level":"DEBUG","time":"2022-07-15T10:22:39.069Z","msg":"Deployments are different:   mongodbatlas.AdvancedCluster{\n  \t... // 13 identical fields\n  \tPitEnabled: &false,\n  \tStateName:  \"IDLE\",\n  \tReplicationSpecs: []*mongodbatlas.AdvancedReplicationSpec{\n  \t\t&{\n  \t\t\tNumShards: 1,\n  \t\t\tID:        \"618cf424edab8f1a9d8c444a\",\n  \t\t\tZoneName:  \"Zone 1\",\n  \t\t\tRegionConfigs: []*mongodbatlas.AdvancedRegionConfig{\n  \t\t\t\t&{\n  \t\t\t\t\tAnalyticsSpecs: &{InstanceSize: \"M10\", NodeCount: &0},\n  \t\t\t\t\tElectableSpecs: &mongodbatlas.Specs{\n  \t\t\t\t\t\tDiskIOPS:      nil,\n  \t\t\t\t\t\tEbsVolumeType: \"\",\n- \t\t\t\t\t\tInstanceSize:  \"M10\",\n+ \t\t\t\t\t\tInstanceSize:  \"M40\",\n  \t\t\t\t\t\tNodeCount:     &3,\n  \t\t\t\t\t},\n  \t\t\t\t\tReadOnlySpecs: &{InstanceSize: \"M10\", NodeCount: &0},\n  \t\t\t\t\tAutoScaling:   &{DiskGB: &{Enabled: &true}, Compute: &{Enabled: &true, ScaleDownEnabled: &true, MinInstanceSize: \"M10\", MaxInstanceSize: \"M40\"}},\n  \t\t\t\t\t... // 4 identical fields\n  \t\t\t\t},\n  \t\t\t},\n  \t\t},\n  \t},\n  \tCreateDate:           \"2021-11-11T10:44:52Z\",\n  \tRootCertType:         \"ISRGROOTX1\",\n  \tVersionReleaseSystem: \"LTS\",\n  }\n","atlasdeployment":"platform/singletons-locking"}
```
**What did you expect?**
1. The `AtlasDeployment` should have been created successfully.
2. If not, ideally the error message should be more appropriate.
3. Also there could be cases where someone might want to change the instance size while upgrading.

**Operator Information**
 - Operator Version - v1.1.0

`kubectl describe output`
```console
Status:
  Conditions:
    Last Transition Time:  2022-07-15T10:25:16Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-07-14T16:26:30Z
    Status:                True
    Type:                  ValidationSucceeded
    Last Transition Time:  2022-07-15T10:25:08Z
    Status:                True
    Type:                  DeploymentReady
  Connection Strings:
    Standard:           mongodb://xxxx:27017,xxxxx:27017,xxxxx:27017/?ssl=true&authSource=admin&replicaSet=atlas-xx-shard-0
    Standard Srv:       mongodb+srv://xxxxxx
  Mongo DB Version:     4.4.15
  Observed Generation:  2
  State Name:           IDLE
Events:
  Type     Reason                       Age                     From             Message
  ----     ------                       ----                    ----             -------
  Warning  DeploymentNotUpdatedInAtlas  12m (x5875 over 17h)    AtlasDeployment  PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/xxxxxxxxxxxxxxx/clusters/locking: 400 (request "ATTRIBUTE_READ_ONLY") The attribute createDate is read-only and cannot be changed by the user.
```

### PR DESCRIPTION
**Pull request by fabritsius**
Closed #606

### CODE REVIEW

**Comment by Freyert** [comment]
@fabritsius we're trying to follow the refactoring and understand how it improves https://github.com/mongodb/mongodb-atlas-kubernetes/issues/606.

It seems there's a larger refactoring you're envisioning? What is it? We'd love to help review/check the refactoring for any issues.

**Comment by fabritsius** [comment]
Hey @Freyert, yeah decided to change the logic a bit, instead of just adding an extra field cleanup. New spec doesn't have fields which cannot be set. This should solve the original issue #606 and potential similar issues in the future.

**Review by igor-karpukhin — APPROVED** [review]
Looks good 👍

**Review by Julien-Ben — APPROVED** [review]
Nice refactoring 👍

**Review by Sugar-pack — APPROVED** [review]
Great work!

**Pull request merged**
