### PR TITLE
CLOUDP-195522: Default cluster bool to false

### PR DESCRIPTION
**Pull request by roothorp**
### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

### CODE REVIEW

**Review by josvazg — APPROVED** [review]
LGTM
Unit tests about it would be nice

**Comment by roothorp** [comment]
@josvazg is this sort of thing OK? I'll admit I'm probably not as familiar with unit testing as I should be - this is just based off what @igor-karpukhin has done for the DataFederation CRD.

**Comment by josvazg** [comment]
> @josvazg is this sort of thing OK? I'll admit I'm probably not as familiar with unit testing as I should be - this is just based off what @igor-karpukhin has done for the DataFederation CRD.
> 
> If so, I can add the equivalent test for the other direction (from Atlas) tomorrow and we should be good to merge :)

LGTM, just one nit pick. As you only have 1 test case you could drop the test case table completely and its loop. Replace it with a `t.Run("title"...` so that your test is still titled. Alternatively you could come with more useful tests cases to add so that the table and loop are actually useful.

**Review by igor-karpukhin — APPROVED** [review]
Looks good 👍

**Review by helderjs — APPROVED** [review]

**Pull request merged**
